# Generated by Django 2.0.1 on 2018-02-24 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateTimeField(verbose_name='Дата окончания действия ссылки активации')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(blank=True, max_length=255, null=True)),
                ('create_date', models.CharField(blank=True, default='24/02, 10:31', max_length=255, null=True)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('preview', models.TextField(blank=True, null=True, verbose_name='Предпросмотр')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('pic', models.TextField(blank=True, null=True)),
                ('categories', models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='mainpage.Categories')),
            ],
            options={
                'verbose_name_plural': 'Посты',
                'verbose_name': 'Пост',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='.', verbose_name='Аватар')),
                ('activation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.Activation', verbose_name='Активация')),
                ('post_fav', models.ManyToManyField(blank=True, to='mainpage.Post')),
            ],
            options={
                'verbose_name_plural': 'Профили',
                'verbose_name': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Сайты',
                'verbose_name': 'Сайт',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categories',
            name='site',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='mainpage.Sites'),
        ),
    ]
